wordpress:
  image: wordpress:fpm
  links:
    - db:mysql
nginx:
  image: wptest
  links:
   - wordpress
  volumes_from:
   - wordpress
  ports:
   - "80:80"
  environment:
    POST_MAX_SIZE: 128m
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: dbpwd123
